# @name signup

POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "name": "Norman Osbourne", 
   "nickname": "Green Goblin", 
   "email": "osbourne@oscorp.com" ,
   "password": "1ihatePeter"
}

###

@id = {{signup.response.body.newUser.id}}

PUT http://localhost:3003/user/edit/{{id}}
Content-Type: application/json

{
   "name": "Harry Osbourne" 
}

###

POST http://localhost:3003/user/login
Content-Type: application/json

{
   "email": "osbourne@oscorp.com" ,
   "password": "1ihatePeter"
}

###

GET http://localhost:3003/user/profile
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlkNWJkNzFiLWJhZDEtNDkxOC1iMDAwLWJhOGIzOTg4ODA5MSIsImlhdCI6MTY3NTIxNTA0NywiZXhwIjoxNjc1MzAxNDQ3fQ.Lvuz34EdD6CmuE99yHvRjOBIfbjao21qJHhmEkPdxxs
Content-Type: application/json
